language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: false
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: ResponseSelector
    epochs: 100
  # - name: SpacyNLP
  #   model: "en_core_web_md"
  #   case_sensitive: false
  # - name: SpacyEntityExtractor
  #   dimensions: ["ORG", "GPE"]
  - name: EntitySynonymMapper
  # - name: "supervised_embeddings"
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 10
  # random_seed: 42 # If you want model to be inititated same when rasa train run
- name: RulePolicy